#!/bin/sh

uci -q batch <<-EOF_UCI >/dev/null
	delete ucitrack.@mqvpn[-1]
	add ucitrack mqvpn
	set ucitrack.@mqvpn[-1].init=mqvpn
	commit ucitrack
EOF_UCI

if [ -z "$(uci -q get network.omrvpn)" ]; then
	uci -q batch <<-EOF_UCI >/dev/null
		set network.omrvpn=interface
		set network.omrvpn.device=mqvpn0
		set network.omrvpn.proto=none
		set network.omrvpn.ip4table=vpn
		set network.omrvpn.multipath=off
		set network.omrvpn.leasetime=12h
		set network.omrvpn.type=tunnel
		set network.omrvpn.txqueuelen=100
		commit network
EOF_UCI
fi

if ! uci -q get ucitrack.@network[-1].affects | grep -q 'mqvpn'; then
	uci -q batch <<-EOF_UCI >/dev/null
		add_list ucitrack.@network[-1].affects='mqvpn'
		commit ucitrack
EOF_UCI
fi

if ! uci -q get firewall.zone_vpn.network | grep -q 'omrvpn'; then
	uci -q batch <<-EOF_UCI >/dev/null
		add_list firewall.zone_vpn.network='omrvpn'
		commit firewall
	EOF_UCI
fi

if ! uci -q get firewall.zone_vpn.device | grep -q 'mqvpn0'; then
	uci -q batch <<-EOF_UCI >/dev/null
		add_list firewall.zone_vpn.device='mqvpn0'
		commit firewall
	EOF_UCI
fi

rm -f /tmp/luci-indexcache
exit 0
