#!/bin/sh
source /etc/os-release
if [ "$ID" = "openmptcprouter" ]; then
	PACKAGE_FEED_VERSION="$VERSION_ID"
	case "$VERSION_ID" in
		v0.62.*-3k-*|v0.62.*-3ktest-*|v0.62.*-3K-*|v0.62.*-3KTest-*)
			PACKAGE_FEED_VERSION="v0.62-6.6"
		;;
	esac
	if [ -f /etc/opkg/customfeeds.conf ]; then
		cat > "/etc/opkg/customfeeds.conf" <<-EOF
		    src/gz openwrt_luci https://packages.openmptcprouter.com/${PACKAGE_FEED_VERSION}/${OPENWRT_ARCH}/luci
		    src/gz openwrt_packages https://packages.openmptcprouter.com/${PACKAGE_FEED_VERSION}/${OPENWRT_ARCH}/packages
		    src/gz openwrt_base https://packages.openmptcprouter.com/${PACKAGE_FEED_VERSION}/${OPENWRT_ARCH}/base
		    src/gz openwrt_routing https://packages.openmptcprouter.com/${PACKAGE_FEED_VERSION}/${OPENWRT_ARCH}/routing
		    src/gz openwrt_telephony https://packages.openmptcprouter.com/${PACKAGE_FEED_VERSION}/${OPENWRT_ARCH}/telephony
		EOF
		TARGET="$(cat /etc/banner | awk '/TARGET/ {print $2}')"
		cat > "/etc/opkg/distfeeds.conf" <<-EOF
		    src/gz openmptcprouter_core https://download.openmptcprouter.com/release/${PACKAGE_FEED_VERSION}/${TARGET}/targets/${OPENWRT_BOARD}/packages
		    src/gz openmptcprouter_base https://download.openmptcprouter.com/release/${PACKAGE_FEED_VERSION}/${TARGET}/packages/${OPENWRT_ARCH}/base
		    src/gz openmptcprouter_luci https://download.openmptcprouter.com/release/${PACKAGE_FEED_VERSION}/${TARGET}/packages/${OPENWRT_ARCH}/luci
		    src/gz openmptcprouter_openmptcprouter https://download.openmptcprouter.com/release/${PACKAGE_FEED_VERSION}/${TARGET}/packages/${OPENWRT_ARCH}/openmptcprouter
		    src/gz openmptcprouter_packages https://download.openmptcprouter.com/release/${PACKAGE_FEED_VERSION}/${TARGET}/packages/${OPENWRT_ARCH}/packages
		EOF
	elif [ -f /etc/apk/repositories.d/distfeeds.list ]; then
		cat > "/etc/apk/repositories.d/customfeeds.list" <<-EOF
		    https://packages.openmptcprouter.com/${PACKAGE_FEED_VERSION}/${OPENWRT_ARCH}/luci/packages.adb
		    https://packages.openmptcprouter.com/${PACKAGE_FEED_VERSION}/${OPENWRT_ARCH}/packages/packages.adb
		    https://packages.openmptcprouter.com/${PACKAGE_FEED_VERSION}/${OPENWRT_ARCH}/base/packages.adb
		    https://packages.openmptcprouter.com/${PACKAGE_FEED_VERSION}/${OPENWRT_ARCH}/routing/packages.adb
		    https://packages.openmptcprouter.com/${PACKAGE_FEED_VERSION}/${OPENWRT_ARCH}/telephony/packages.adb
		EOF
		TARGET="$(cat /etc/banner | awk '/TARGET/ {print $2}')"
		cat > "/etc/apk/repositories.d/distfeeds.list" <<-EOF
		    https://download.openmptcprouter.com/release/${PACKAGE_FEED_VERSION}/${TARGET}/targets/${OPENWRT_BOARD}/packages/packages.adb
		    https://download.openmptcprouter.com/release/${PACKAGE_FEED_VERSION}/${TARGET}/packages/${OPENWRT_ARCH}/base/packages.adb
		    https://download.openmptcprouter.com/release/${PACKAGE_FEED_VERSION}/${TARGET}/packages/${OPENWRT_ARCH}/luci/packages.adb
		    https://download.openmptcprouter.com/release/${PACKAGE_FEED_VERSION}/${TARGET}/packages/${OPENWRT_ARCH}/openmptcprouter/packages.adb
		    https://download.openmptcprouter.com/release/${PACKAGE_FEED_VERSION}/${TARGET}/packages/${OPENWRT_ARCH}/packages/packages.adb
		EOF
	fi
fi
